let map_data = {
  st1: {
    id: 1,
    name: 'Alabama',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st2: {
    id: 2,
    name: 'Alaska',
    shortname: '0 ',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st3: {
    id: 3,
    name: 'Arizona',
    shortname: '0 ',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st4: {
    id: 4,
    name: 'Arkansas',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st5: {
    id: 5,
    name: 'California',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st6: {
    id: 6,
    name: 'Colorado',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st7: {
    id: 7,
    name: 'Connecticut',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st8: {
    id: 8,
    name: 'Delaware',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st9: {
    id: 9,
    name: 'District of Columbia',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st10: {
    id: 10,
    name: 'Florida',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st11: {
    id: 11,
    name: 'Georgia',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st12: {
    id: 12,
    name: 'Hawaii',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st13: {
    id: 13,
    name: 'Idaho',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st14: {
    id: 14,
    name: 'Illinois',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st15: {
    id: 15,
    name: 'Indiana',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st16: {
    id: 16,
    name: 'Iowa',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st17: {
    id: 17,
    name: 'Kansas',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st18: {
    id: 18,
    name: 'Kentucky',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st19: {
    id: 19,
    name: 'Louisiana',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st20: {
    id: 20,
    name: 'Maine',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st21: {
    id: 21,
    name: 'Maryland',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st22: {
    id: 22,
    name: 'Massachusetts',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st23: {
    id: 23,
    name: 'Michigan',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st24: {
    id: 24,
    name: 'Minnesota',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st25: {
    id: 25,
    name: 'Mississippi',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st26: {
    id: 26,
    name: 'Missouri',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st27: {
    id: 27,
    name: 'Montana',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st28: {
    id: 28,
    name: 'Nebraska',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st29: {
    id: 29,
    name: 'Nevada',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st30: {
    id: 30,
    name: 'New Hampshire',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st31: {
    id: 31,
    name: 'New Jersey',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st32: {
    id: 32,
    name: 'New Mexico',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st33: {
    id: 33,
    name: 'New York',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st34: {
    id: 34,
    name: 'North Carolina',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st35: {
    id: 35,
    name: 'North Dakota',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st36: {
    id: 36,
    name: 'Ohio',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st37: {
    id: 37,
    name: 'Oklahoma',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st38: {
    id: 38,
    name: 'Oregon',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st39: {
    id: 39,
    name: 'Pennsylvania',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st40: {
    id: 40,
    name: 'Rhode Island',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st41: {
    id: 41,
    name: 'South Carolina',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st42: {
    id: 42,
    name: 'South Dakota',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st43: {
    id: 43,
    name: 'Tennessee',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st44: {
    id: 44,
    name: 'Texas',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st45: {
    id: 45,
    name: 'Utah',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st46: {
    id: 46,
    name: 'Vermont',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st47: {
    id: 47,
    name: 'Virginia',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st48: {
    id: 48,
    name: 'Washington',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st49: {
    id: 49,
    name: 'West Virginia',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st50: {
    id: 50,
    name: 'Wisconsin',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
  st51: {
    id: 51,
    name: 'Wyoming',
    shortname: '0',
    link: '',
    comment: '',
    image: '',
    color_map: '#3e95cd',
    color_map_over: '#366CA3',
  },
}
